server:
  port: 8206
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    password: root
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.109.128
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  rabbitmq:
    host: 192.168.109.128
    password: guest
    username: guest
    port: 5672
    virtual-host: /
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/yygh/orders/mapper/xml/*.xml
#开启对sentinel的支持
feign:
  hystrix:
    enabled: true
  client: #超时时间设置
    config:
      default:
        connect-timeout: 50000
        read-timeout: 50000

weipay:
  #关联的公众号appid
  appid: wx74862e0dfcf69954
  #商户号
  partner: 1558950191
  #商户key
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  cret: 'E:\Java\yygh\yygh_parent\service\service_orders\src\main\resources\cert\apiclient_cert.p12'
