# 服务端口
server:
  port: 8204


spring:
  application:
    # 服务名
    name: service-sms
    # 环境设置：dev、test、prod
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #redis配置
  redis:
    host: 192.168.109.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间,负数表示一直等
        max-idle: 5
        min-idle: 0

  rabbitmq:
    host: 192.168.109.128
    password: guest
    username: guest
    port: 5672
    virtual-host: /